[WIP] sb/intel: Fix flashconsole on older architectures
Building coreboot with CONSOLE_SPI_FLASH on Sandybridge (and others) fails
with the following errors:

build/romstage/drivers/spi/spi-generic.o: In function `spi_setup_slave':
src/drivers/spi/spi-generic.c:119: undefined reference to `spi_ctrlr_bus_map'
src/drivers/spi/spi-generic.c:121: undefined reference to `spi_ctrlr_bus_map_count'
src/drivers/spi/spi-generic.c:124: undefined reference to `spi_ctrlr_bus_map'

This is due to the fact that sb/intel/common/spi.c is currently not built
in romstage, but drivers/spi/spi-generic.c requires it.

In this commit sb/intel/common/spi.c is adapted to the romstage and it is
added to it.

Change-Id: Ifd3e8621fa4cb349b7e0e07118cab0380f24ff55
Signed-off-by: Nicola Corna <nicola@corna.info>